package com.mission.shop.order.dao.mapper;

import com.mission.shop.order.dao.model.OrderStatus;
import com.mission.shop.order.dao.model.OrderStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int countByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int deleteByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int insert(OrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int insertSelective(OrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    List<OrderStatus> selectByExample(OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    OrderStatus selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int updateByExampleSelective(@Param("record") OrderStatus record, @Param("example") OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int updateByExample(@Param("record") OrderStatus record, @Param("example") OrderStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int updateByPrimaryKeySelective(OrderStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    int updateByPrimaryKey(OrderStatus record);
}