package com.mission.shop.product.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GoodsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public GoodsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andGoodsIdIsNull() {
			addCriterion("goods_id is null");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIsNotNull() {
			addCriterion("goods_id is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsIdEqualTo(Long value) {
			addCriterion("goods_id =", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotEqualTo(Long value) {
			addCriterion("goods_id <>", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdGreaterThan(Long value) {
			addCriterion("goods_id >", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdGreaterThanOrEqualTo(Long value) {
			addCriterion("goods_id >=", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdLessThan(Long value) {
			addCriterion("goods_id <", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdLessThanOrEqualTo(Long value) {
			addCriterion("goods_id <=", value, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdIn(List<Long> values) {
			addCriterion("goods_id in", values, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotIn(List<Long> values) {
			addCriterion("goods_id not in", values, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdBetween(Long value1, Long value2) {
			addCriterion("goods_id between", value1, value2, "goodsId");
			return (Criteria) this;
		}

		public Criteria andGoodsIdNotBetween(Long value1, Long value2) {
			addCriterion("goods_id not between", value1, value2, "goodsId");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("product_id is null");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("product_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductIdEqualTo(Long value) {
			addCriterion("product_id =", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotEqualTo(Long value) {
			addCriterion("product_id <>", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThan(Long value) {
			addCriterion("product_id >", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Long value) {
			addCriterion("product_id >=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThan(Long value) {
			addCriterion("product_id <", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Long value) {
			addCriterion("product_id <=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdIn(List<Long> values) {
			addCriterion("product_id in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotIn(List<Long> values) {
			addCriterion("product_id not in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdBetween(Long value1, Long value2) {
			addCriterion("product_id between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotBetween(Long value1, Long value2) {
			addCriterion("product_id not between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andGoodsSnIsNull() {
			addCriterion("goods_sn is null");
			return (Criteria) this;
		}

		public Criteria andGoodsSnIsNotNull() {
			addCriterion("goods_sn is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsSnEqualTo(String value) {
			addCriterion("goods_sn =", value, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnNotEqualTo(String value) {
			addCriterion("goods_sn <>", value, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnGreaterThan(String value) {
			addCriterion("goods_sn >", value, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnGreaterThanOrEqualTo(String value) {
			addCriterion("goods_sn >=", value, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnLessThan(String value) {
			addCriterion("goods_sn <", value, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnLessThanOrEqualTo(String value) {
			addCriterion("goods_sn <=", value, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnLike(String value) {
			addCriterion("goods_sn like", value, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnNotLike(String value) {
			addCriterion("goods_sn not like", value, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnIn(List<String> values) {
			addCriterion("goods_sn in", values, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnNotIn(List<String> values) {
			addCriterion("goods_sn not in", values, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnBetween(String value1, String value2) {
			addCriterion("goods_sn between", value1, value2, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andGoodsSnNotBetween(String value1, String value2) {
			addCriterion("goods_sn not between", value1, value2, "goodsSn");
			return (Criteria) this;
		}

		public Criteria andSpecIsNull() {
			addCriterion("spec is null");
			return (Criteria) this;
		}

		public Criteria andSpecIsNotNull() {
			addCriterion("spec is not null");
			return (Criteria) this;
		}

		public Criteria andSpecEqualTo(String value) {
			addCriterion("spec =", value, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecNotEqualTo(String value) {
			addCriterion("spec <>", value, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecGreaterThan(String value) {
			addCriterion("spec >", value, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecGreaterThanOrEqualTo(String value) {
			addCriterion("spec >=", value, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecLessThan(String value) {
			addCriterion("spec <", value, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecLessThanOrEqualTo(String value) {
			addCriterion("spec <=", value, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecLike(String value) {
			addCriterion("spec like", value, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecNotLike(String value) {
			addCriterion("spec not like", value, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecIn(List<String> values) {
			addCriterion("spec in", values, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecNotIn(List<String> values) {
			addCriterion("spec not in", values, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecBetween(String value1, String value2) {
			addCriterion("spec between", value1, value2, "spec");
			return (Criteria) this;
		}

		public Criteria andSpecNotBetween(String value1, String value2) {
			addCriterion("spec not between", value1, value2, "spec");
			return (Criteria) this;
		}

		public Criteria andStockIsNull() {
			addCriterion("stock is null");
			return (Criteria) this;
		}

		public Criteria andStockIsNotNull() {
			addCriterion("stock is not null");
			return (Criteria) this;
		}

		public Criteria andStockEqualTo(Integer value) {
			addCriterion("stock =", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockNotEqualTo(Integer value) {
			addCriterion("stock <>", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockGreaterThan(Integer value) {
			addCriterion("stock >", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockGreaterThanOrEqualTo(Integer value) {
			addCriterion("stock >=", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockLessThan(Integer value) {
			addCriterion("stock <", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockLessThanOrEqualTo(Integer value) {
			addCriterion("stock <=", value, "stock");
			return (Criteria) this;
		}

		public Criteria andStockIn(List<Integer> values) {
			addCriterion("stock in", values, "stock");
			return (Criteria) this;
		}

		public Criteria andStockNotIn(List<Integer> values) {
			addCriterion("stock not in", values, "stock");
			return (Criteria) this;
		}

		public Criteria andStockBetween(Integer value1, Integer value2) {
			addCriterion("stock between", value1, value2, "stock");
			return (Criteria) this;
		}

		public Criteria andStockNotBetween(Integer value1, Integer value2) {
			addCriterion("stock not between", value1, value2, "stock");
			return (Criteria) this;
		}

		public Criteria andSalesIsNull() {
			addCriterion("sales is null");
			return (Criteria) this;
		}

		public Criteria andSalesIsNotNull() {
			addCriterion("sales is not null");
			return (Criteria) this;
		}

		public Criteria andSalesEqualTo(Integer value) {
			addCriterion("sales =", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotEqualTo(Integer value) {
			addCriterion("sales <>", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesGreaterThan(Integer value) {
			addCriterion("sales >", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesGreaterThanOrEqualTo(Integer value) {
			addCriterion("sales >=", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesLessThan(Integer value) {
			addCriterion("sales <", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesLessThanOrEqualTo(Integer value) {
			addCriterion("sales <=", value, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesIn(List<Integer> values) {
			addCriterion("sales in", values, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotIn(List<Integer> values) {
			addCriterion("sales not in", values, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesBetween(Integer value1, Integer value2) {
			addCriterion("sales between", value1, value2, "sales");
			return (Criteria) this;
		}

		public Criteria andSalesNotBetween(Integer value1, Integer value2) {
			addCriterion("sales not between", value1, value2, "sales");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Integer value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Integer value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Integer value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Integer value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Integer value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Integer> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Integer> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Integer value1, Integer value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceIsNull() {
			addCriterion("display_price is null");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceIsNotNull() {
			addCriterion("display_price is not null");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceEqualTo(Integer value) {
			addCriterion("display_price =", value, "displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceNotEqualTo(Integer value) {
			addCriterion("display_price <>", value, "displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceGreaterThan(Integer value) {
			addCriterion("display_price >", value, "displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("display_price >=", value, "displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceLessThan(Integer value) {
			addCriterion("display_price <", value, "displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceLessThanOrEqualTo(Integer value) {
			addCriterion("display_price <=", value, "displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceIn(List<Integer> values) {
			addCriterion("display_price in", values, "displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceNotIn(List<Integer> values) {
			addCriterion("display_price not in", values, "displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceBetween(Integer value1, Integer value2) {
			addCriterion("display_price between", value1, value2,
					"displayPrice");
			return (Criteria) this;
		}

		public Criteria andDisplayPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("display_price not between", value1, value2,
					"displayPrice");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andVersionIsNull() {
			addCriterion("version is null");
			return (Criteria) this;
		}

		public Criteria andVersionIsNotNull() {
			addCriterion("version is not null");
			return (Criteria) this;
		}

		public Criteria andVersionEqualTo(Integer value) {
			addCriterion("version =", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotEqualTo(Integer value) {
			addCriterion("version <>", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThan(Integer value) {
			addCriterion("version >", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("version >=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThan(Integer value) {
			addCriterion("version <", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionLessThanOrEqualTo(Integer value) {
			addCriterion("version <=", value, "version");
			return (Criteria) this;
		}

		public Criteria andVersionIn(List<Integer> values) {
			addCriterion("version in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotIn(List<Integer> values) {
			addCriterion("version not in", values, "version");
			return (Criteria) this;
		}

		public Criteria andVersionBetween(Integer value1, Integer value2) {
			addCriterion("version between", value1, value2, "version");
			return (Criteria) this;
		}

		public Criteria andVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("version not between", value1, value2, "version");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table goods
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table goods
     *
     * @mbggenerated do_not_delete_during_merge Thu Jun 12 11:22:43 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}