package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class PicUrl implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pic_url.id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pic_url.pic_url
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pic_url.pic_desc
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String picDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pic_url.pic_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String picName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pic_url.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pic_url.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pic_url.status
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pic_url
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pic_url.id
	 * @return  the value of pic_url.id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pic_url.id
	 * @param id  the value for pic_url.id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pic_url.pic_url
	 * @return  the value of pic_url.pic_url
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pic_url.pic_url
	 * @param picUrl  the value for pic_url.pic_url
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl == null ? null : picUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pic_url.pic_desc
	 * @return  the value of pic_url.pic_desc
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getPicDesc() {
		return picDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pic_url.pic_desc
	 * @param picDesc  the value for pic_url.pic_desc
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setPicDesc(String picDesc) {
		this.picDesc = picDesc == null ? null : picDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pic_url.pic_name
	 * @return  the value of pic_url.pic_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getPicName() {
		return picName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pic_url.pic_name
	 * @param picName  the value for pic_url.pic_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setPicName(String picName) {
		this.picName = picName == null ? null : picName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pic_url.create_time
	 * @return  the value of pic_url.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pic_url.create_time
	 * @param createTime  the value for pic_url.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pic_url.update_time
	 * @return  the value of pic_url.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pic_url.update_time
	 * @param updateTime  the value for pic_url.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pic_url.status
	 * @return  the value of pic_url.status
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pic_url.status
	 * @param status  the value for pic_url.status
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}
}