package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Product implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.kind_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Long kindId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.shop_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Long shopId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.shop_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String shopName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_sn
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String productSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.product_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.brand_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Long brandId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.brand_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.view_num
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Long viewNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.status
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.pay_type
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Integer payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_id
	 * @return  the value of product.product_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_id
	 * @param productId  the value for product.product_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.kind_id
	 * @return  the value of product.kind_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Long getKindId() {
		return kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.kind_id
	 * @param kindId  the value for product.kind_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setKindId(Long kindId) {
		this.kindId = kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.shop_id
	 * @return  the value of product.shop_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Long getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.shop_id
	 * @param shopId  the value for product.shop_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setShopId(Long shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.shop_name
	 * @return  the value of product.shop_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.shop_name
	 * @param shopName  the value for product.shop_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName == null ? null : shopName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_sn
	 * @return  the value of product.product_sn
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getProductSn() {
		return productSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_sn
	 * @param productSn  the value for product.product_sn
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setProductSn(String productSn) {
		this.productSn = productSn == null ? null : productSn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.product_name
	 * @return  the value of product.product_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.product_name
	 * @param productName  the value for product.product_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.brand_id
	 * @return  the value of product.brand_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Long getBrandId() {
		return brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.brand_id
	 * @param brandId  the value for product.brand_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setBrandId(Long brandId) {
		this.brandId = brandId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.brand_name
	 * @return  the value of product.brand_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.brand_name
	 * @param brandName  the value for product.brand_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName == null ? null : brandName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.view_num
	 * @return  the value of product.view_num
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Long getViewNum() {
		return viewNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.view_num
	 * @param viewNum  the value for product.view_num
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setViewNum(Long viewNum) {
		this.viewNum = viewNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.status
	 * @return  the value of product.status
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.status
	 * @param status  the value for product.status
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.pay_type
	 * @return  the value of product.pay_type
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Integer getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.pay_type
	 * @param payType  the value for product.pay_type
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.create_time
	 * @return  the value of product.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.create_time
	 * @param createTime  the value for product.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.update_time
	 * @return  the value of product.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.update_time
	 * @param updateTime  the value for product.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}