package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class ProductAttr implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.id
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.product_id
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	private Long productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.attr_name
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	private String attrName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.attr_value
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	private String attrValue;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.sort_order
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	private Integer sortOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.create_time
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_attr.last_update_time
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table product_attr
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.id
	 * @return  the value of product_attr.id
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.id
	 * @param id  the value for product_attr.id
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.product_id
	 * @return  the value of product_attr.product_id
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.product_id
	 * @param productId  the value for product_attr.product_id
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.attr_name
	 * @return  the value of product_attr.attr_name
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public String getAttrName() {
		return attrName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.attr_name
	 * @param attrName  the value for product_attr.attr_name
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public void setAttrName(String attrName) {
		this.attrName = attrName == null ? null : attrName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.attr_value
	 * @return  the value of product_attr.attr_value
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public String getAttrValue() {
		return attrValue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.attr_value
	 * @param attrValue  the value for product_attr.attr_value
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue == null ? null : attrValue.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.sort_order
	 * @return  the value of product_attr.sort_order
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public Integer getSortOrder() {
		return sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.sort_order
	 * @param sortOrder  the value for product_attr.sort_order
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.create_time
	 * @return  the value of product_attr.create_time
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.create_time
	 * @param createTime  the value for product_attr.create_time
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_attr.last_update_time
	 * @return  the value of product_attr.last_update_time
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_attr.last_update_time
	 * @param lastUpdateTime  the value for product_attr.last_update_time
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}
}