package com.mission.shop.product.dao.model;

import java.io.Serializable;
import java.util.Date;

public class SpecAttr implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column spec_attr.spec_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Long specId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column spec_attr.kind_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Long kindId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column spec_attr.spec_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String specName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column spec_attr.spec_values
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private String specValues;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column spec_attr.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column spec_attr.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table spec_attr
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column spec_attr.spec_id
	 * @return  the value of spec_attr.spec_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Long getSpecId() {
		return specId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column spec_attr.spec_id
	 * @param specId  the value for spec_attr.spec_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setSpecId(Long specId) {
		this.specId = specId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column spec_attr.kind_id
	 * @return  the value of spec_attr.kind_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Long getKindId() {
		return kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column spec_attr.kind_id
	 * @param kindId  the value for spec_attr.kind_id
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setKindId(Long kindId) {
		this.kindId = kindId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column spec_attr.spec_name
	 * @return  the value of spec_attr.spec_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getSpecName() {
		return specName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column spec_attr.spec_name
	 * @param specName  the value for spec_attr.spec_name
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setSpecName(String specName) {
		this.specName = specName == null ? null : specName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column spec_attr.spec_values
	 * @return  the value of spec_attr.spec_values
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public String getSpecValues() {
		return specValues;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column spec_attr.spec_values
	 * @param specValues  the value for spec_attr.spec_values
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setSpecValues(String specValues) {
		this.specValues = specValues == null ? null : specValues.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column spec_attr.create_time
	 * @return  the value of spec_attr.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column spec_attr.create_time
	 * @param createTime  the value for spec_attr.create_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column spec_attr.update_time
	 * @return  the value of spec_attr.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column spec_attr.update_time
	 * @param updateTime  the value for spec_attr.update_time
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}