package com.mission.shop.user.dao.model;

import java.io.Serializable;

public class Area implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.area_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Long areaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.area_name
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private String areaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.parent_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column area.level
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Integer level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.area_id
	 * @return  the value of area.area_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Long getAreaId() {
		return areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.area_id
	 * @param areaId  the value for area.area_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setAreaId(Long areaId) {
		this.areaId = areaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.area_name
	 * @return  the value of area.area_name
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public String getAreaName() {
		return areaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.area_name
	 * @param areaName  the value for area.area_name
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setAreaName(String areaName) {
		this.areaName = areaName == null ? null : areaName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.parent_id
	 * @return  the value of area.parent_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.parent_id
	 * @param parentId  the value for area.parent_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column area.level
	 * @return  the value of area.level
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Integer getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column area.level
	 * @param level  the value for area.level
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setLevel(Integer level) {
		this.level = level;
	}
}