package com.mission.shop.user.dao.model;

import java.io.Serializable;
import java.util.Date;

public class UserIntegral implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.user_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.order_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Long orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.user_name
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.create_time
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.update_time
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.integral
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Integer integral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.type
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_integral.remark
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_integral
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.id
	 * @return  the value of user_integral.id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.id
	 * @param id  the value for user_integral.id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.user_id
	 * @return  the value of user_integral.user_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.user_id
	 * @param userId  the value for user_integral.user_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.order_id
	 * @return  the value of user_integral.order_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.order_id
	 * @param orderId  the value for user_integral.order_id
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.user_name
	 * @return  the value of user_integral.user_name
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.user_name
	 * @param userName  the value for user_integral.user_name
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.create_time
	 * @return  the value of user_integral.create_time
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.create_time
	 * @param createTime  the value for user_integral.create_time
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.update_time
	 * @return  the value of user_integral.update_time
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.update_time
	 * @param updateTime  the value for user_integral.update_time
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.integral
	 * @return  the value of user_integral.integral
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Integer getIntegral() {
		return integral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.integral
	 * @param integral  the value for user_integral.integral
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setIntegral(Integer integral) {
		this.integral = integral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.type
	 * @return  the value of user_integral.type
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.type
	 * @param type  the value for user_integral.type
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_integral.remark
	 * @return  the value of user_integral.remark
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_integral.remark
	 * @param remark  the value for user_integral.remark
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}