package com.mission.shop.user.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserRankExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public UserRankExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRankIdIsNull() {
			addCriterion("rank_id is null");
			return (Criteria) this;
		}

		public Criteria andRankIdIsNotNull() {
			addCriterion("rank_id is not null");
			return (Criteria) this;
		}

		public Criteria andRankIdEqualTo(Integer value) {
			addCriterion("rank_id =", value, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdNotEqualTo(Integer value) {
			addCriterion("rank_id <>", value, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdGreaterThan(Integer value) {
			addCriterion("rank_id >", value, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("rank_id >=", value, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdLessThan(Integer value) {
			addCriterion("rank_id <", value, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdLessThanOrEqualTo(Integer value) {
			addCriterion("rank_id <=", value, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdIn(List<Integer> values) {
			addCriterion("rank_id in", values, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdNotIn(List<Integer> values) {
			addCriterion("rank_id not in", values, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdBetween(Integer value1, Integer value2) {
			addCriterion("rank_id between", value1, value2, "rankId");
			return (Criteria) this;
		}

		public Criteria andRankIdNotBetween(Integer value1, Integer value2) {
			addCriterion("rank_id not between", value1, value2, "rankId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andRankIsNull() {
			addCriterion("rank is null");
			return (Criteria) this;
		}

		public Criteria andRankIsNotNull() {
			addCriterion("rank is not null");
			return (Criteria) this;
		}

		public Criteria andRankEqualTo(Integer value) {
			addCriterion("rank =", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotEqualTo(Integer value) {
			addCriterion("rank <>", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankGreaterThan(Integer value) {
			addCriterion("rank >", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankGreaterThanOrEqualTo(Integer value) {
			addCriterion("rank >=", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankLessThan(Integer value) {
			addCriterion("rank <", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankLessThanOrEqualTo(Integer value) {
			addCriterion("rank <=", value, "rank");
			return (Criteria) this;
		}

		public Criteria andRankIn(List<Integer> values) {
			addCriterion("rank in", values, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotIn(List<Integer> values) {
			addCriterion("rank not in", values, "rank");
			return (Criteria) this;
		}

		public Criteria andRankBetween(Integer value1, Integer value2) {
			addCriterion("rank between", value1, value2, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNotBetween(Integer value1, Integer value2) {
			addCriterion("rank not between", value1, value2, "rank");
			return (Criteria) this;
		}

		public Criteria andRankNameIsNull() {
			addCriterion("rank_name is null");
			return (Criteria) this;
		}

		public Criteria andRankNameIsNotNull() {
			addCriterion("rank_name is not null");
			return (Criteria) this;
		}

		public Criteria andRankNameEqualTo(String value) {
			addCriterion("rank_name =", value, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameNotEqualTo(String value) {
			addCriterion("rank_name <>", value, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameGreaterThan(String value) {
			addCriterion("rank_name >", value, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameGreaterThanOrEqualTo(String value) {
			addCriterion("rank_name >=", value, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameLessThan(String value) {
			addCriterion("rank_name <", value, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameLessThanOrEqualTo(String value) {
			addCriterion("rank_name <=", value, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameLike(String value) {
			addCriterion("rank_name like", value, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameNotLike(String value) {
			addCriterion("rank_name not like", value, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameIn(List<String> values) {
			addCriterion("rank_name in", values, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameNotIn(List<String> values) {
			addCriterion("rank_name not in", values, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameBetween(String value1, String value2) {
			addCriterion("rank_name between", value1, value2, "rankName");
			return (Criteria) this;
		}

		public Criteria andRankNameNotBetween(String value1, String value2) {
			addCriterion("rank_name not between", value1, value2, "rankName");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table user_rank
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_rank
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 16 13:10:32 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}