package com.mission.shop.product.dao.mapper;

import com.mission.shop.product.dao.model.Brand;
import com.mission.shop.product.dao.model.BrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrandMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int countByExample(BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int deleteByExample(BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int deleteByPrimaryKey(Long brandId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int insert(Brand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int insertSelective(Brand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	List<Brand> selectByExample(BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	Brand selectByPrimaryKey(Long brandId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Brand record,
			@Param("example") BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int updateByExample(@Param("record") Brand record,
			@Param("example") BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int updateByPrimaryKeySelective(Brand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbggenerated  Mon Jun 16 13:18:26 CST 2014
	 */
	int updateByPrimaryKey(Brand record);
}