package com.mission.shop.product.dao.mapper;

import com.mission.shop.product.dao.model.ProductComent;
import com.mission.shop.product.dao.model.ProductComentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductComentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int countByExample(ProductComentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int deleteByExample(ProductComentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int insert(ProductComent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int insertSelective(ProductComent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	List<ProductComent> selectByExample(ProductComentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	ProductComent selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int updateByExampleSelective(@Param("record") ProductComent record,
			@Param("example") ProductComentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int updateByExample(@Param("record") ProductComent record,
			@Param("example") ProductComentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int updateByPrimaryKeySelective(ProductComent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_coment
	 * @mbggenerated  Thu Jun 12 16:14:17 CST 2014
	 */
	int updateByPrimaryKey(ProductComent record);
}