package com.mission.shop.user.dao.mapper;

import com.mission.shop.user.dao.model.Area;
import com.mission.shop.user.dao.model.AreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AreaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int countByExample(AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int deleteByExample(AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int deleteByPrimaryKey(Long areaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int insert(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int insertSelective(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	List<Area> selectByExample(AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	Area selectByPrimaryKey(Long areaId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int updateByExampleSelective(@Param("record") Area record,
			@Param("example") AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int updateByExample(@Param("record") Area record,
			@Param("example") AreaExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int updateByPrimaryKeySelective(Area record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table area
	 * @mbggenerated  Mon Jun 16 13:12:54 CST 2014
	 */
	int updateByPrimaryKey(Area record);
}