package com.mission.shop.order.dao.model;

import java.io.Serializable;
import java.util.Date;

public class Express implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.express_id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Long expressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.express_name
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private String expressName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.create_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.update_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.telephone
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.contact
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.contact_phone_num
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private String contactPhoneNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table express
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.express_id
     *
     * @return the value of express.express_id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Long getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.express_id
     *
     * @param expressId the value for express.express_id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setExpressId(Long expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.express_name
     *
     * @return the value of express.express_name
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public String getExpressName() {
        return expressName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.express_name
     *
     * @param expressName the value for express.express_name
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setExpressName(String expressName) {
        this.expressName = expressName == null ? null : expressName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.status
     *
     * @return the value of express.status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.status
     *
     * @param status the value for express.status
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.create_time
     *
     * @return the value of express.create_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.create_time
     *
     * @param createTime the value for express.create_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.update_time
     *
     * @return the value of express.update_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.update_time
     *
     * @param updateTime the value for express.update_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.telephone
     *
     * @return the value of express.telephone
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.telephone
     *
     * @param telephone the value for express.telephone
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.contact
     *
     * @return the value of express.contact
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.contact
     *
     * @param contact the value for express.contact
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.contact_phone_num
     *
     * @return the value of express.contact_phone_num
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public String getContactPhoneNum() {
        return contactPhoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.contact_phone_num
     *
     * @param contactPhoneNum the value for express.contact_phone_num
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setContactPhoneNum(String contactPhoneNum) {
        this.contactPhoneNum = contactPhoneNum == null ? null : contactPhoneNum.trim();
    }
}