package com.mission.shop.order.dao.model;

import java.io.Serializable;
import java.util.Date;

public class OrderGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.price
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.quanity
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Integer quanity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.create_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.update_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_goods.goods_name
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_goods
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.id
     *
     * @return the value of order_goods.id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.id
     *
     * @param id the value for order_goods.id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_id
     *
     * @return the value of order_goods.goods_id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_id
     *
     * @param goodsId the value for order_goods.goods_id
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.price
     *
     * @return the value of order_goods.price
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.price
     *
     * @param price the value for order_goods.price
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.quanity
     *
     * @return the value of order_goods.quanity
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Integer getQuanity() {
        return quanity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.quanity
     *
     * @param quanity the value for order_goods.quanity
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setQuanity(Integer quanity) {
        this.quanity = quanity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.create_time
     *
     * @return the value of order_goods.create_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.create_time
     *
     * @param createTime the value for order_goods.create_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.update_time
     *
     * @return the value of order_goods.update_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.update_time
     *
     * @param updateTime the value for order_goods.update_time
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_goods.goods_name
     *
     * @return the value of order_goods.goods_name
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_goods.goods_name
     *
     * @param goodsName the value for order_goods.goods_name
     *
     * @mbggenerated Tue Jun 17 17:11:38 CST 2014
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }
}